/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sesuaitugas.gui;

import com.mycompany.sesuaitugas.objects.User;
import com.mycompany.sesuaitugas.services.LoginService;
import com.mycompany.sesuaitugas.util.I18nManager;

import java.awt.Color;
import java.util.Locale;
import java.util.prefs.Preferences;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private final LoginService loginService;
    private static final String PREFS_EMAIL = "login_email";
    private static final String PREFS_REMEMBER = "login_remember";

    /** Echo character untuk menyembunyikan kata sandi (disimpan sebelum placeholder). */
    private char passwordEchoChar = '\u2022';

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        loginService = new LoginService();
        loginService.ensureDefaultAdmin();
        loginService.ensureDefaultMahasiswa();
        com.mycompany.sesuaitugas.util.SeedDummyData.seed();
        setupListeners();
        setupPlaceholders();
        restoreRememberMe();
        refreshUIText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnLanguageID = new javax.swing.JButton();
        btnLanguageEN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(2008, 1200));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 750));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Masuk Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Selamat datang kembali! Silakan masukkan detail Anda.");

        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("nim@kampus.id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Kata Sandi");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Masukan NIM / Email");

        jPasswordField1.setText("jPasswordField1");

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox2.setText("Tampilkan kata sandi");

        jCheckBox1.setText("Ingat saya selama 30 hari");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        btnLanguageID.setBackground(new java.awt.Color(240, 240, 224));
        btnLanguageID.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnLanguageID.setText("🇮🇩 ID");
        btnLanguageID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanguageIDActionPerformed(evt);
            }
        });

        btnLanguageEN.setBackground(new java.awt.Color(240, 240, 224));
        btnLanguageEN.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnLanguageEN.setText("🇬🇧 EN");
        btnLanguageEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanguageENActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Masuk ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLanguageID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLanguageEN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLanguageID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLanguageEN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1037, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed



    // ─── Login Logic (non-generated) ────────────────────────────────────────────

    /**
     * Menambahkan ActionListener pada tombol "Masuk" dan Enter key pada password field.
     */
    private void setupListeners() {
        // Klik tombol "Masuk"
        jButton1.addActionListener(e -> performLogin());

        // Tekan Enter di password field langsung login
        jPasswordField1.addActionListener(e -> performLogin());

        jCheckBox2.addActionListener(e -> applyPasswordEchoMode());
    }

    /**
     * Menampilkan atau menyembunyikan karakter kata sandi sesuai checkbox (placeholder tetap teks biasa).
     */
    private void applyPasswordEchoMode() {
        final String passwordPlaceholder = "Masukkan kata sandi";
        String current = new String(jPasswordField1.getPassword());
        if (current.equals(passwordPlaceholder)) {
            jPasswordField1.setEchoChar((char) 0);
            return;
        }
        if (jCheckBox2.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar(passwordEchoChar);
        }
    }

    /**
     * Merestore email/NIM dari Preferences jika "Ingat saya" pernah dicentang.
     */
    private void restoreRememberMe() {
        Preferences prefs = Preferences.userNodeForPackage(Login.class);
        String savedEmail = prefs.get(PREFS_EMAIL, "");
        boolean remember = prefs.getBoolean(PREFS_REMEMBER, false);
        if (remember && !savedEmail.isEmpty() && savedEmail.equals(jTextField1.getText())) {
            // Hanya restore jika field masih placeholder
            jTextField1.setText(savedEmail);
            jTextField1.setForeground(Color.BLACK);
            jCheckBox1.setSelected(true);
        }
    }



    /**
     * Setup placeholder text behaviour untuk email & password fields.
     */
    private void setupPlaceholders() {
        final String emailPlaceholder = "nim@kampus.id";
        final String passwordPlaceholder = "Masukkan kata sandi";
        final java.awt.Color placeholderColor = new java.awt.Color(153, 153, 153);
        final java.awt.Color normalColor = java.awt.Color.BLACK;

        // ── Email field placeholder ──
        jTextField1.setForeground(placeholderColor);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (jTextField1.getText().equals(emailPlaceholder)) {
                    jTextField1.setText("");
                    jTextField1.setForeground(normalColor);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (jTextField1.getText().trim().isEmpty()) {
                    jTextField1.setForeground(placeholderColor);
                    jTextField1.setText(emailPlaceholder);
                }
            }
        });

        // ── Password field placeholder ──
        // Simpan echoChar asli, lalu tampilkan placeholder sebagai teks biasa
        passwordEchoChar = jPasswordField1.getEchoChar();
        if (passwordEchoChar == 0) {
            passwordEchoChar = '\u2022';
        }
        jPasswordField1.setEchoChar((char) 0);  // tampilkan teks, bukan dots
        jPasswordField1.setText(passwordPlaceholder);
        jPasswordField1.setForeground(placeholderColor);

        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                String current = new String(jPasswordField1.getPassword());
                if (current.equals(passwordPlaceholder)) {
                    jPasswordField1.setText("");
                    applyPasswordEchoMode();
                    jPasswordField1.setForeground(normalColor);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                String current = new String(jPasswordField1.getPassword());
                if (current.trim().isEmpty()) {
                    jPasswordField1.setEchoChar((char) 0); // tampilkan teks
                    jPasswordField1.setForeground(placeholderColor);
                    jPasswordField1.setText(passwordPlaceholder);
                } else {
                    applyPasswordEchoMode();
                }
            }
        });
    }

    /**
     * Melakukan proses login:
     * 1. Ambil email & password dari field
     * 2. Validasi via LoginService
     * 3. Jika berhasil → simpan Remember Me, buka panel, tutup Login
     * 4. Jika gagal → tampilkan pesan error
     */
    private void performLogin() {
        String email = jTextField1.getText().trim();
        String password = new String(jPasswordField1.getPassword());

        // Validasi input kosong
        if (email.isEmpty() || email.equals("nim@kampus.id")) {
            JOptionPane.showMessageDialog(this,
                    "Silakan masukkan email Anda.",
                    "Email Kosong", JOptionPane.WARNING_MESSAGE);
            jTextField1.requestFocus();
            return;
        }
        if (password.isEmpty() || password.equals("Masukkan kata sandi")) {
            JOptionPane.showMessageDialog(this,
                    "Silakan masukkan kata sandi Anda.",
                    "Password Kosong", JOptionPane.WARNING_MESSAGE);
            jPasswordField1.requestFocus();
            return;
        }

        // 1) Coba autentikasi sebagai admin (koleksi admin, pakai email)
        User adminUser = loginService.authenticate(email, password);
        if (adminUser != null) {
            simpanRememberMe(email);
            openAdminDashboard(adminUser);
            return;
        }

        // 2) Coba autentikasi sebagai mahasiswa (koleksi mahasiswa, pakai NIM + password)
        com.mycompany.sesuaitugas.objects.Mahasiswa mhs = loginService.authenticateMahasiswa(email, password);
        if (mhs != null) {
            simpanRememberMe(email);
            openMahasiswaPage(mhs);
            return;
        }

        // 3) Gagal
        JOptionPane.showMessageDialog(this,
                "Email/NIM atau kata sandi salah. Silakan coba lagi.",
                "Login Gagal", JOptionPane.ERROR_MESSAGE);
        jPasswordField1.setText("");
        jPasswordField1.requestFocus();
    }

    /**
     * Menyimpan atau menghapus email dari Preferences sesuai centang "Ingat saya".
     */
    private void simpanRememberMe(String email) {
        Preferences prefs = Preferences.userNodeForPackage(Login.class);
        if (jCheckBox1.isSelected()) {
            prefs.put(PREFS_EMAIL, email);
            prefs.putBoolean(PREFS_REMEMBER, true);
        } else {
            prefs.remove(PREFS_EMAIL);
            prefs.putBoolean(PREFS_REMEMBER, false);
        }
    }

    private void openAdminDashboard(User user) {
        String greet = user.getNama() != null && !user.getNama().trim().isEmpty()
                ? user.getNama().trim()
                : user.getEmail();
        JOptionPane.showMessageDialog(this,
                "Login berhasil! Selamat datang, " + greet + " (Admin)",
                "Berhasil", JOptionPane.INFORMATION_MESSAGE);
        try {
            JFrame adminFrame = new JFrame("Admin Dashboard");
            adminFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            adminFrame.setContentPane(new Admin(user));
            adminFrame.pack();
            adminFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            adminFrame.setLocationRelativeTo(null);
            adminFrame.setVisible(true);
            this.dispose();
        } catch (Throwable ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal membuka halaman Admin", ex);
            JOptionPane.showMessageDialog(this,
                    "Gagal membuka halaman admin: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void openMahasiswaPage(com.mycompany.sesuaitugas.objects.Mahasiswa mhs) {
        String greet = mhs.getNama() != null && !mhs.getNama().trim().isEmpty()
                ? mhs.getNama().trim()
                : mhs.getNim();
        JOptionPane.showMessageDialog(this,
                "Login berhasil! Selamat datang, " + greet + " (Mahasiswa)",
                "Berhasil", JOptionPane.INFORMATION_MESSAGE);
        try {
            Mahasiswa mahasiswaFrame = new Mahasiswa(mhs);
            mahasiswaFrame.setVisible(true);
            this.dispose();
        } catch (Throwable ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal membuka halaman Mahasiswa", ex);
            JOptionPane.showMessageDialog(this,
                    "Gagal membuka halaman mahasiswa: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Tambah tombol ganti bahasa (ID/EN) di atas form login.
     */
    /**
     * Refresh semua text UI sesuai locale yang dipilih.
     */
    private void refreshUIText() {
        jLabel1.setText(I18nManager.get("login.title"));
        jLabel2.setText(I18nManager.get("login.subtitle"));
        jLabel3.setText(I18nManager.get("login.passwordLabel"));
        jLabel4.setText(I18nManager.get("login.nimLabel"));
        jCheckBox2.setText(I18nManager.get("login.showPassword"));
        jCheckBox1.setText(I18nManager.get("login.rememberMe"));
        jButton1.setText(I18nManager.get("login.buttonLogin"));
        setTitle(I18nManager.get("app.title"));
    }

    /**
     * Event handler untuk tombol ID.
     */
    private void btnLanguageIDActionPerformed(java.awt.event.ActionEvent evt) {
        I18nManager.setLocale(new Locale("id", "ID"));
        refreshUIText();
    }

    /**
     * Event handler untuk tombol EN.
     */
    private void btnLanguageENActionPerformed(java.awt.event.ActionEvent evt) {
        I18nManager.setLocale(new Locale("en", "US"));
        refreshUIText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanguageEN;
    private javax.swing.JButton btnLanguageID;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
