/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sesuaitugas.gui;

import com.mycompany.sesuaitugas.services.MahasiswaService;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 * Halaman absensi RFID/NFC untuk mahasiswa.
 * Mahasiswa menempelkan kartu atau memasukkan NIM manual,
 * lalu sistem mencari data di koleksi {@code mahasiswa} dan mencatat kehadiran.
 *
 * @author mnish
 */
public class Mahasiswa extends javax.swing.JFrame {

    private final MahasiswaService mahasiswaService = new MahasiswaService();
    private DefaultTableModel logTableModel;

    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa() {
        initComponents();

        // Ukuran 1 layar (bukan fullscreen/maximized)
        java.awt.Dimension screen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screen.width, screen.height);
        jPanel1.setPreferredSize(new java.awt.Dimension(screen.width, screen.height));
        setLocationRelativeTo(null);

        setupClock();
        setupLogTable();
        setupListeners();
        txtRfidInput.requestFocusInWindow();
    }

    // ── Jam real-time ──

    private void setupClock() {
        updateClockLabels();
        Timer clockTimer = new Timer(1000, e -> updateClockLabels());
        clockTimer.start();
    }

    private void updateClockLabels() {
        Date now = new Date();
        lblClock.setText(new SimpleDateFormat("HH:mm:ss").format(now));
        lblDate.setText(new SimpleDateFormat("EEEE, dd MMMM yyyy", new Locale("id", "ID")).format(now));
    }

    // ── Log tabel ──

    private void setupLogTable() {
        logTableModel = (DefaultTableModel) tblLog.getModel();
    }

    // ── Listener tombol & Enter ──

    private void setupListeners() {
        btnScan.addActionListener(e -> onScan());
        txtRfidInput.addActionListener(e -> onScan());
        btnLogout.addActionListener(e -> onLogout());
    }

    // ── Logika scan ──

    private void onScan() {
        String input = txtRfidInput.getText().trim();
        if (input.isEmpty()) {
            showStatus("Masukkan ID RFID / NFC terlebih dahulu.", new Color(204, 0, 0));
            return;
        }

        // Cari mahasiswa berdasarkan NIM (simulasi RFID → NIM mapping)
        com.mycompany.sesuaitugas.objects.Mahasiswa mhs = mahasiswaService.findByNim(input);

        if (mhs == null) {
            showStatus("Mahasiswa tidak ditemukan!", new Color(204, 0, 0));
            clearInfoPanel();
            txtRfidInput.selectAll();
            return;
        }

        // Tampilkan info mahasiswa
        lblNamaValue.setText(nullToEmpty(mhs.getNama()));
        lblNimValue.setText(nullToEmpty(mhs.getNim()));
        lblJurusanValue.setText(nullToEmpty(mhs.getJurusan()));
        lblIdValue.setText(nullToEmpty(mhs.getIdMahasiswa()));

        // Catat ke log tabel
        String waktu = new SimpleDateFormat("HH:mm:ss").format(new Date());
        logTableModel.insertRow(0, new Object[]{
            waktu,
            mhs.getNim(),
            mhs.getNama(),
            "HADIR"
        });

        showStatus("Absensi berhasil!", new Color(0, 153, 0));
        lblStatusTime.setText("Tercatat pukul " + waktu);

        txtRfidInput.setText("");
        txtRfidInput.requestFocusInWindow();
    }

    private void showStatus(String message, Color color) {
        lblStatus.setText(message);
        lblStatus.setForeground(color);
    }

    private void clearInfoPanel() {
        lblNamaValue.setText("-");
        lblNimValue.setText("-");
        lblJurusanValue.setText("-");
        lblIdValue.setText("-");
        lblStatusTime.setText("");
    }

    private void onLogout() {
        this.dispose();
        new Login().setVisible(true);
    }

    private static String nullToEmpty(String s) {
        return s == null || s.trim().isEmpty() ? "-" : s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRfidLabel = new javax.swing.JLabel();
        txtRfidInput = new javax.swing.JTextField();
        btnScan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        lblNamaLabel = new javax.swing.JLabel();
        lblNamaValue = new javax.swing.JLabel();
        lblNimLabel = new javax.swing.JLabel();
        lblNimValue = new javax.swing.JLabel();
        lblJurusanLabel = new javax.swing.JLabel();
        lblJurusanValue = new javax.swing.JLabel();
        lblIdLabel = new javax.swing.JLabel();
        lblIdValue = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblStatusTime = new javax.swing.JLabel();
        lblLogTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLog = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Absensi RFID - Mahasiswa");

        jPanel1.setBackground(new java.awt.Color(240, 248, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(1870, 1200));
        jPanel1.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(25, 55, 95));
        lblTitle.setText("Absensi RFID / NFC");
        jPanel1.add(lblTitle);
        lblTitle.setBounds(60, 30, 500, 60);

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(128, 128, 128));
        lblSubtitle.setText("Tempelkan kartu RFID/NFC atau masukkan NIM secara manual");
        jPanel1.add(lblSubtitle);
        lblSubtitle.setBounds(60, 90, 600, 35);

        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblClock.setForeground(new java.awt.Color(0, 102, 204));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClock.setText("00:00:00");
        jPanel1.add(lblClock);
        lblClock.setBounds(1400, 30, 400, 50);

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDate.setForeground(new java.awt.Color(128, 128, 128));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDate.setText("Sabtu, 17 Mei 2026");
        jPanel1.add(lblDate);
        lblDate.setBounds(1400, 80, 400, 30);

        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 140, 1870, 2);

        lblRfidLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblRfidLabel.setText("RFID / NFC ID :");
        jPanel1.add(lblRfidLabel);
        lblRfidLabel.setBounds(60, 170, 200, 50);

        txtRfidInput.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtRfidInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRfidInput);
        txtRfidInput.setBounds(270, 170, 700, 55);

        btnScan.setBackground(new java.awt.Color(0, 51, 255));
        btnScan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnScan.setForeground(new java.awt.Color(255, 255, 255));
        btnScan.setText("Scan / Absen");
        jPanel1.add(btnScan);
        btnScan.setBounds(1000, 170, 300, 55);

        btnLogout.setBackground(new java.awt.Color(204, 51, 51));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        jPanel1.add(btnLogout);
        btnLogout.setBounds(1350, 175, 130, 45);

        panelInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(
            null, "Informasi Mahasiswa",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        panelInfo.setLayout(null);

        lblNamaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaLabel.setText("Nama :");
        panelInfo.add(lblNamaLabel);
        lblNamaLabel.setBounds(30, 40, 120, 35);

        lblNamaValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNamaValue.setText("-");
        panelInfo.add(lblNamaValue);
        lblNamaValue.setBounds(160, 40, 500, 35);

        lblNimLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNimLabel.setText("NIM :");
        panelInfo.add(lblNimLabel);
        lblNimLabel.setBounds(30, 85, 120, 35);

        lblNimValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNimValue.setText("-");
        panelInfo.add(lblNimValue);
        lblNimValue.setBounds(160, 85, 500, 35);

        lblJurusanLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJurusanLabel.setText("Jurusan :");
        panelInfo.add(lblJurusanLabel);
        lblJurusanLabel.setBounds(30, 130, 120, 35);

        lblJurusanValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJurusanValue.setText("-");
        panelInfo.add(lblJurusanValue);
        lblJurusanValue.setBounds(160, 130, 500, 35);

        lblIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIdLabel.setText("ID :");
        panelInfo.add(lblIdLabel);
        lblIdLabel.setBounds(30, 175, 120, 35);

        lblIdValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdValue.setText("-");
        panelInfo.add(lblIdValue);
        lblIdValue.setBounds(160, 175, 500, 35);

        jPanel1.add(panelInfo);
        panelInfo.setBounds(60, 260, 700, 280);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(128, 128, 128));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Menunggu scan...");
        jPanel1.add(lblStatus);
        lblStatus.setBounds(800, 300, 600, 80);

        lblStatusTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStatusTime.setForeground(new java.awt.Color(128, 128, 128));
        lblStatusTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusTime.setText("");
        jPanel1.add(lblStatusTime);
        lblStatusTime.setBounds(800, 380, 600, 35);

        lblLogTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogTitle.setText("Riwayat Absensi Hari Ini");
        jPanel1.add(lblLogTitle);
        lblLogTitle.setBounds(60, 570, 350, 40);

        tblLog.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Waktu", "NIM", "Nama", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLog.setRowHeight(30);
        jScrollPane1.setViewportView(tblLog);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 620, 1750, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnScan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblIdLabel;
    private javax.swing.JLabel lblIdValue;
    private javax.swing.JLabel lblJurusanLabel;
    private javax.swing.JLabel lblJurusanValue;
    private javax.swing.JLabel lblLogTitle;
    private javax.swing.JLabel lblNamaLabel;
    private javax.swing.JLabel lblNamaValue;
    private javax.swing.JLabel lblNimLabel;
    private javax.swing.JLabel lblNimValue;
    private javax.swing.JLabel lblRfidLabel;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusTime;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JTable tblLog;
    private javax.swing.JTextField txtRfidInput;
    // End of variables declaration//GEN-END:variables
}